---
version: "3.7"

services:
  opensmm-web:
    image: sintelli/opensmm-web:latest
    container_name: opensmm-web
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - opensmm-api
    environment:
      DOMAIN: ${DOMAIN}
      SSL_KEY: ${SSL_KEY}
      SSL_CRT: ${SSL_CRT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      API_PORT: ${API_PORT}
    security_opt:
      - no-new-privileges:true
    networks:
      opensmm:
        ipv4_address: ${DOCKER_SUBNET}.2

  opensmm-api:
    image: sintelli/opensmm-api:latest
    container_name: opensmm-api
    restart: unless-stopped
    depends_on:
      - opensmm-db
      - opensmm-redis
    environment:
      DOMAIN: ${DOMAIN}
      CORS_ALLOWED: ${API_CORS_ALLOWED}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_NAME: ${DATABASE_NAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      API_PORT: ${API_PORT}
      SECRET_1: ${SECRET_1}
      SECRET_2: ${SECRET_2}
      TWITTER_CLIENT_ID: ${TWITTER_CLIENT_ID}
      TWITTER_CLIENT_SECRET: ${TWITTER_CLIENT_SECRET}
      TIMEZONE_OFFSET: ${TIMEZONE_OFFSET}
      DEBUG: ${DEBUG}
    volumes:
      - ./data/api:/data
      - ./data/logs:/logs
    security_opt:
      - no-new-privileges:true
    networks:
      opensmm:
        ipv4_address: ${DOCKER_SUBNET}.3

  opensmm-db:
    image: mongo:latest
    container_name: opensmm-db
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./data/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/mongo/db:/data/db
    # Ports exposed for debugging purposes
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      opensmm:
        ipv4_address: ${DOCKER_SUBNET}.4

  opensmm-redis:
    image: redis:alpine
    container_name: opensmm-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data/redis/data:/var/lib/redis
      - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      opensmm:
        ipv4_address: ${DOCKER_SUBNET}.5

networks:
  opensmm:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET}.0/16
          gateway: ${DOCKER_SUBNET}.1
